name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:
    - name: Deploy to DockerHub
      if: github.ref == 'refs/heads/main'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        BASE_VERSION=$(cat version.txt)
        export IMAGE_TAG=$BASE_VERSION.$(date -u '+%Y%m%d%H%M')
        echo $BASE_VERSION
        echo $IMAGE_TAG
        echo $IMAGE_TAG > IMAGE_TAG
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        make all