# This workflow builds and uploads a the docker image
# It's only meant to be manually invoked when the automated python-docker-publish.yml
# file errors out and the image needs to be rebuilt.

name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "docker image tag"
        required: true
        type: string

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Docker Setup Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0
      - name: Build and push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ inputs.tag }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker buildx build . --push --file dockerfiles/Dockerfile \
          --tag netapp/astra-toolkits:latest --tag netapp/astra-toolkits:$DOCKERIMAGE_TAG \
          --platform linux/amd64,linux/arm64
