# This workflow builds and uploads a the docker image
# It's only meant to be manually invoked when the automated python-docker-publish.yml
# file errors out and the image needs to be rebuilt.

name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag'
        required: true
        type: string

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.9.0
    - name: Build and push the Docker image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker buildx build . --push --file Dockerfile \
        --tag netapp/astra-toolkits:latest --tag netapp/astra-toolkits:$DOCKERIMAGE_TAG \
        --platform linux/amd64,linux/arm64
