# This workflow builds and uploads a the docker image
# It's only meant to be manually invoked when the automated python-docker-publish.yml
# file errors out and the image needs to be rebuilt.

name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag'
        required: true
        type: string

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker build . --file Dockerfile --tag netapp/astra-toolkits:latest --tag netapp/astra-toolkits:$DOCKERIMAGE_TAG
    - name: Push the Docker image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERIMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        docker push netapp/astra-toolkits:latest
        docker push netapp/astra-toolkits:$DOCKERIMAGE_TAG
